-- V18: Seed locked historical payroll periods from nomina PDFs.
-- Generated by scripts/seed_payroll_from_nomina_pdfs.py
-- Periods: 5 | Entries: 72

INSERT INTO employees (tenant_id, full_name, active)
SELECT 1, seed.full_name, true
FROM (VALUES
  ('ARTURO'),
  ('CARLOS R.'),
  ('CHORE'),
  ('CRISTAL'),
  ('CRISTIAN'),
  ('DAVID'),
  ('ERASMO'),
  ('LUPE'),
  ('MANUEL'),
  ('PANCHO'),
  ('REINA'),
  ('RICARDO'),
  ('TAVO'),
  ('VALE'),
  ('WENDY'),
  ('WICHO'),
  ('YUREM')
) AS seed(full_name)
WHERE NOT EXISTS (
  SELECT 1 FROM employees e
  WHERE e.tenant_id = 1 AND e.full_name = seed.full_name
);

-- Payroll period 2026-04-05 to 2026-04-11
INSERT INTO payroll_periods (tenant_id, start_date, end_date, status, computed_at, locked_at)
VALUES (1, '2026-04-05', '2026-04-11', 'LOCKED', now(), now())
ON CONFLICT (tenant_id, start_date, end_date) DO UPDATE
SET status = 'LOCKED',
    computed_at = COALESCE(payroll_periods.computed_at, excluded.computed_at),
    locked_at = COALESCE(payroll_periods.locked_at, excluded.locked_at),
    updated_at = now();

-- Payroll period 2026-04-12 to 2026-04-18
INSERT INTO payroll_periods (tenant_id, start_date, end_date, status, computed_at, locked_at)
VALUES (1, '2026-04-12', '2026-04-18', 'LOCKED', now(), now())
ON CONFLICT (tenant_id, start_date, end_date) DO UPDATE
SET status = 'LOCKED',
    computed_at = COALESCE(payroll_periods.computed_at, excluded.computed_at),
    locked_at = COALESCE(payroll_periods.locked_at, excluded.locked_at),
    updated_at = now();

-- Payroll period 2026-04-19 to 2026-04-25
INSERT INTO payroll_periods (tenant_id, start_date, end_date, status, computed_at, locked_at)
VALUES (1, '2026-04-19', '2026-04-25', 'LOCKED', now(), now())
ON CONFLICT (tenant_id, start_date, end_date) DO UPDATE
SET status = 'LOCKED',
    computed_at = COALESCE(payroll_periods.computed_at, excluded.computed_at),
    locked_at = COALESCE(payroll_periods.locked_at, excluded.locked_at),
    updated_at = now();

-- Payroll period 2026-04-26 to 2026-05-02
INSERT INTO payroll_periods (tenant_id, start_date, end_date, status, computed_at, locked_at)
VALUES (1, '2026-04-26', '2026-05-02', 'LOCKED', now(), now())
ON CONFLICT (tenant_id, start_date, end_date) DO UPDATE
SET status = 'LOCKED',
    computed_at = COALESCE(payroll_periods.computed_at, excluded.computed_at),
    locked_at = COALESCE(payroll_periods.locked_at, excluded.locked_at),
    updated_at = now();

-- Payroll period 2026-05-03 to 2026-05-09
INSERT INTO payroll_periods (tenant_id, start_date, end_date, status, computed_at, locked_at)
VALUES (1, '2026-05-03', '2026-05-09', 'LOCKED', now(), now())
ON CONFLICT (tenant_id, start_date, end_date) DO UPDATE
SET status = 'LOCKED',
    computed_at = COALESCE(payroll_periods.computed_at, excluded.computed_at),
    locked_at = COALESCE(payroll_periods.locked_at, excluded.locked_at),
    updated_at = now();

WITH seed AS (
  SELECT * FROM (VALUES
    ('2026-04-05'::date, '2026-04-11'::date, 'YUREM', 31.00, 1540.00, 10.65, 330.00, 0.00, 0.00, 758.00, 1112.00),
    ('2026-04-05'::date, '2026-04-11'::date, 'WENDY', 15.00, 915.30, 61.02, 0.00, 0.00, 0.00, 249.00, 666.30),
    ('2026-04-05'::date, '2026-04-11'::date, 'LUPE', 18.00, 991.70, 55.09, 0.00, 0.00, 0.00, 35.00, 956.70),
    ('2026-04-05'::date, '2026-04-11'::date, 'CRISTAL', 21.00, 0.00, 30.00, 0.00, 630.00, 0.00, 100.00, 530.00),
    ('2026-04-05'::date, '2026-04-11'::date, 'ERASMO', 30.00, 0.00, 30.00, 0.00, 900.00, 0.00, 0.00, 900.00),
    ('2026-04-05'::date, '2026-04-11'::date, 'ARTURO', 37.00, 0.00, 30.00, 0.00, 2110.00, 0.00, 1000.00, 1110.00),
    ('2026-04-05'::date, '2026-04-11'::date, 'VALE', 20.00, 0.00, 30.00, 0.00, 600.00, 0.00, 0.00, 600.00),
    ('2026-04-05'::date, '2026-04-11'::date, 'CHORE', 22.00, 0.00, 30.00, 0.00, 660.00, 0.00, 0.00, 660.00),
    ('2026-04-05'::date, '2026-04-11'::date, 'PANCHO', 19.00, 0.00, 30.00, 0.00, 570.00, 0.00, 106.00, 464.00),
    ('2026-04-05'::date, '2026-04-11'::date, 'MANUEL', 21.00, 0.00, 30.00, 0.00, 630.00, 0.00, 75.00, 555.00),
    ('2026-04-05'::date, '2026-04-11'::date, 'WICHO', 6.00, 0.00, 30.00, 0.00, 180.00, 0.00, 0.00, 180.00),
    ('2026-04-05'::date, '2026-04-11'::date, 'TAVO', 12.00, 0.00, 30.00, 0.00, 360.00, 0.00, 131.00, 229.00),
    ('2026-04-05'::date, '2026-04-11'::date, 'CARLOS R.', 0.00, 2800.00, 0.00, 0.00, 200.00, 0.00, 0.00, 3000.00),
    ('2026-04-05'::date, '2026-04-11'::date, 'REINA', 14.00, 2196.00, 28.57, 400.00, 0.00, 0.00, 2000.00, 596.00),
    ('2026-04-12'::date, '2026-04-18'::date, 'YUREM', 52.00, 1490.00, 11.31, 588.00, 0.00, 0.00, 1161.00, 917.00),
    ('2026-04-12'::date, '2026-04-18'::date, 'WENDY', 38.00, 1183.30, 31.14, 0.00, 0.00, 0.00, 270.00, 913.30),
    ('2026-04-12'::date, '2026-04-18'::date, 'LUPE', 12.00, 330.50, 27.54, 0.00, 0.00, 0.00, 0.00, 330.50),
    ('2026-04-12'::date, '2026-04-18'::date, 'CRISTAL', 34.00, 0.00, 30.00, 0.00, 1020.00, 0.00, 18.00, 1002.00),
    ('2026-04-12'::date, '2026-04-18'::date, 'ERASMO', 55.00, 0.00, 30.00, 0.00, 1650.00, 0.00, 500.00, 1150.00),
    ('2026-04-12'::date, '2026-04-18'::date, 'ARTURO', 67.00, 0.00, 30.00, 0.00, 2010.00, 0.00, 950.00, 1060.00),
    ('2026-04-12'::date, '2026-04-18'::date, 'VALE', 53.00, 0.00, 30.00, 0.00, 1590.00, 0.00, 35.00, 1555.00),
    ('2026-04-12'::date, '2026-04-18'::date, 'CHORE', 63.00, 0.00, 30.00, 0.00, 1890.00, 0.00, 1890.00, 0.00),
    ('2026-04-12'::date, '2026-04-18'::date, 'PANCHO', 47.00, 0.00, 30.00, 0.00, 1410.00, 0.00, 70.00, 1340.00),
    ('2026-04-12'::date, '2026-04-18'::date, 'MANUEL', 44.00, 0.00, 30.00, 0.00, 1320.00, 0.00, 35.00, 1285.00),
    ('2026-04-12'::date, '2026-04-18'::date, 'WICHO', 12.00, 0.00, 30.00, 0.00, 360.00, 0.00, 0.00, 360.00),
    ('2026-04-12'::date, '2026-04-18'::date, 'TAVO', 32.00, 0.00, 30.00, 0.00, 960.00, 0.00, 890.00, 70.00),
    ('2026-04-12'::date, '2026-04-18'::date, 'CARLOS R.', 0.00, 2800.00, 0.00, 0.00, 200.00, 0.00, 0.00, 3000.00),
    ('2026-04-12'::date, '2026-04-18'::date, 'REINA', 27.00, 2564.00, 28.70, 775.00, 0.00, 0.00, 2500.00, 839.00),
    ('2026-04-19'::date, '2026-04-25'::date, 'YUREM', 53.00, 1500.00, 13.92, 738.00, 0.00, 0.00, 1069.00, 1169.00),
    ('2026-04-19'::date, '2026-04-25'::date, 'WENDY', 20.00, 600.00, 30.00, 0.00, 0.00, 0.00, 305.00, 295.00),
    ('2026-04-19'::date, '2026-04-25'::date, 'LUPE', 13.00, 416.70, 32.05, 0.00, 0.00, 0.00, 240.00, 176.70),
    ('2026-04-19'::date, '2026-04-25'::date, 'CRISTAL', 34.00, 0.00, 30.00, 0.00, 1020.00, 0.00, 283.00, 737.00),
    ('2026-04-19'::date, '2026-04-25'::date, 'ERASMO', 45.00, 0.00, 30.00, 0.00, 1350.00, 0.00, 500.00, 850.00),
    ('2026-04-19'::date, '2026-04-25'::date, 'ARTURO', 52.00, 0.00, 30.00, 0.00, 1860.00, 0.00, 1239.00, 621.00),
    ('2026-04-19'::date, '2026-04-25'::date, 'VALE', 43.00, 0.00, 30.00, 0.00, 1290.00, 0.00, 0.00, 1290.00),
    ('2026-04-19'::date, '2026-04-25'::date, 'CHORE', 45.00, 0.00, 30.00, 0.00, 1350.00, 0.00, 0.00, 1350.00),
    ('2026-04-19'::date, '2026-04-25'::date, 'PANCHO', 35.00, 0.00, 30.00, 0.00, 1050.00, 0.00, 200.00, 850.00),
    ('2026-04-19'::date, '2026-04-25'::date, 'MANUEL', 39.00, 0.00, 30.00, 0.00, 1170.00, 0.00, 235.00, 935.00),
    ('2026-04-19'::date, '2026-04-25'::date, 'WICHO', 17.00, 0.00, 30.00, 0.00, 510.00, 0.00, 255.00, 255.00),
    ('2026-04-19'::date, '2026-04-25'::date, 'TAVO', 4.00, 0.00, 30.00, 0.00, 120.00, 0.00, 120.00, 0.00),
    ('2026-04-19'::date, '2026-04-25'::date, 'CARLOS R.', 0.00, 2800.00, 0.00, 0.00, 200.00, 0.00, 0.00, 3000.00),
    ('2026-04-19'::date, '2026-04-25'::date, 'REINA', 31.00, 2564.00, 27.58, 855.00, 0.00, 0.00, 2500.00, 919.00),
    ('2026-04-26'::date, '2026-05-02'::date, 'YUREM', 55.00, 1500.00, 9.05, 498.00, 0.00, 0.00, 1024.00, 974.00),
    ('2026-04-26'::date, '2026-05-02'::date, 'WENDY', 26.00, 790.20, 30.39, 0.00, 0.00, 0.00, 309.00, 481.20),
    ('2026-04-26'::date, '2026-05-02'::date, 'LUPE', 58.00, 1412.50, 24.35, 0.00, 0.00, 0.00, 33.00, 1379.50),
    ('2026-04-26'::date, '2026-05-02'::date, 'CRISTAL', 31.00, 0.00, 30.00, 0.00, 930.00, 0.00, 0.00, 930.00),
    ('2026-04-26'::date, '2026-05-02'::date, 'ERASMO', 53.00, 0.00, 30.00, 0.00, 1590.00, 0.00, 500.00, 1090.00),
    ('2026-04-26'::date, '2026-05-02'::date, 'ARTURO', 43.00, 0.00, 30.00, 0.00, 1290.00, 0.00, 739.00, 551.00),
    ('2026-04-26'::date, '2026-05-02'::date, 'VALE', 46.00, 0.00, 30.00, 0.00, 1380.00, 0.00, 0.00, 1380.00),
    ('2026-04-26'::date, '2026-05-02'::date, 'CHORE', 47.00, 0.00, 30.00, 0.00, 1410.00, 0.00, 35.00, 1375.00),
    ('2026-04-26'::date, '2026-05-02'::date, 'PANCHO', 43.00, 0.00, 30.00, 0.00, 1290.00, 0.00, 340.00, 950.00),
    ('2026-04-26'::date, '2026-05-02'::date, 'MANUEL', 45.00, 0.00, 30.00, 0.00, 1350.00, 0.00, 0.00, 1350.00),
    ('2026-04-26'::date, '2026-05-02'::date, 'WICHO', 16.00, 0.00, 30.00, 0.00, 480.00, 0.00, 18.00, 462.00),
    ('2026-04-26'::date, '2026-05-02'::date, 'DAVID', 45.00, 0.00, 30.00, 0.00, 1350.00, 0.00, 109.00, 1241.00),
    ('2026-04-26'::date, '2026-05-02'::date, 'CRISTIAN', 44.00, 0.00, 30.00, 0.00, 1320.00, 0.00, 175.00, 1145.00),
    ('2026-04-26'::date, '2026-05-02'::date, 'CARLOS R.', 0.00, 2800.00, 0.00, 0.00, 200.00, 0.00, 0.00, 3000.00),
    ('2026-04-26'::date, '2026-05-02'::date, 'REINA', 18.00, 2564.00, 28.33, 510.00, 0.00, 0.00, 2000.00, 1074.00),
    ('2026-05-03'::date, '2026-05-09'::date, 'YUREM', 45.50, 1730.00, 11.93, 543.00, 0.00, 0.00, 794.00, 1479.00),
    ('2026-05-03'::date, '2026-05-09'::date, 'LUPE', 53.00, 1254.20, 23.66, 0.00, 0.00, 0.00, 33.00, 1221.20),
    ('2026-05-03'::date, '2026-05-09'::date, 'CRISTAL', 24.00, 0.00, 30.00, 0.00, 720.00, 0.00, 239.00, 481.00),
    ('2026-05-03'::date, '2026-05-09'::date, 'ERASMO', 57.00, 0.00, 30.00, 0.00, 1710.00, 0.00, 758.00, 952.00),
    ('2026-05-03'::date, '2026-05-09'::date, 'ARTURO', 2.00, 0.00, 30.00, 0.00, 60.00, 0.00, 0.00, 60.00),
    ('2026-05-03'::date, '2026-05-09'::date, 'VALE', 15.00, 0.00, 30.00, 0.00, 450.00, 0.00, 0.00, 450.00),
    ('2026-05-03'::date, '2026-05-09'::date, 'CHORE', 46.00, 0.00, 30.00, 0.00, 1380.00, 0.00, 535.00, 845.00),
    ('2026-05-03'::date, '2026-05-09'::date, 'PANCHO', 38.00, 0.00, 30.00, 0.00, 1140.00, 0.00, 135.00, 1005.00),
    ('2026-05-03'::date, '2026-05-09'::date, 'MANUEL', 40.00, 0.00, 30.00, 0.00, 1200.00, 0.00, 100.00, 1100.00),
    ('2026-05-03'::date, '2026-05-09'::date, 'WICHO', 17.00, 0.00, 30.00, 0.00, 510.00, 0.00, 0.00, 510.00),
    ('2026-05-03'::date, '2026-05-09'::date, 'DAVID', 50.00, 0.00, 30.00, 0.00, 1500.00, 0.00, 141.00, 1359.00),
    ('2026-05-03'::date, '2026-05-09'::date, 'CRISTIAN', 48.00, 0.00, 30.00, 0.00, 1440.00, 0.00, 0.00, 1440.00),
    ('2026-05-03'::date, '2026-05-09'::date, 'RICARDO', 18.00, 0.00, 30.00, 0.00, 540.00, 0.00, 203.00, 337.00),
    ('2026-05-03'::date, '2026-05-09'::date, 'CARLOS R.', 0.00, 2800.00, 0.00, 0.00, 200.00, 0.00, 0.00, 3000.00),
    ('2026-05-03'::date, '2026-05-09'::date, 'REINA', 22.50, 2564.00, 28.56, 642.50, 0.00, 0.00, 1000.00, 2206.50)
  ) AS v(start_date, end_date, employee_name, cars_washed, base_salary,
       cars_bonus_rate, cars_bonus, commissions, tips_pool_share, advances_deducted, net_pay)
)
INSERT INTO payroll_entries (
  tenant_id, payroll_period_id, employee_id, cars_washed, base_salary, cars_bonus_rate,
  cars_bonus, commissions, tips_pool_share, advances_deducted, net_pay
)
SELECT
  1, pp.id, e.id, seed.cars_washed, seed.base_salary, seed.cars_bonus_rate,
  seed.cars_bonus, seed.commissions, seed.tips_pool_share, seed.advances_deducted, seed.net_pay
FROM seed
JOIN payroll_periods pp
  ON pp.tenant_id = 1 AND pp.start_date = seed.start_date AND pp.end_date = seed.end_date
JOIN employees e
  ON e.tenant_id = 1 AND e.full_name = seed.employee_name
ON CONFLICT (tenant_id, payroll_period_id, employee_id) DO UPDATE
SET cars_washed = excluded.cars_washed,
    base_salary = excluded.base_salary,
    cars_bonus_rate = excluded.cars_bonus_rate,
    cars_bonus = excluded.cars_bonus,
    commissions = excluded.commissions,
    tips_pool_share = excluded.tips_pool_share,
    advances_deducted = excluded.advances_deducted,
    net_pay = excluded.net_pay,
    updated_at = now();
